### ISSUE TITLE
devtools failed install due to DESCRIPTION malformed authors

### ISSUE THREAD

**Issue by Astahlke** [samyeaman/dgconstraint#3]
Howdy authors, 

Thanks for making this package available! Installation via devtools failed for me when using the devtools method:
`>devtools::install_github("samyeaman/dgconstraint", build_vignettes = TRUE)`

returns:
`a-information ... ERROR

E> Malformed Authors@R field:  

E>   <text>:2:26: unexpected ','

E> 1: person("Sam", "Yeaman", email = "samuel.yeaman@ucalgary.ca",

E> 2:   role = c("aut", "cre")),

E>                             ^

E> 

E> See section 'The DESCRIPTION file' in the 'Writing R Extensions'

E> manual.

E> `

Looks like an easy fix. I think it's just missing the c() for multiple authors, eg:
`Authors@R: c(
    person("Sam", "Yeaman", email = "samuel.yeaman@ucalgary.ca",  role = c("aut", "cre")),
    person("Aleeza", "Gerstein", email = "Aleeza.Gerstein@umanitoba.ca", role = c("aut", "cre")))`

I succesfully installed with
`remotes::install_github("alanaschick/dgconstraint", build = TRUE, build_opts = c("--no-resave-data", "--no-manual"), force = T)`

Wanted to give you all a heads up. Thanks!

Amanda

**Comment by Astahlke** [comment]
P.S. I couldn't get the vignettes or help docs to install via remotes, so I forked the repo to make this 'quick fix' - realized you can only have one author designated as creator [cre]. Was able to install including vignettes after removing the creator tags from authors other than yeaman. I didn't merge my branch because co-authors may want to do something differently. Hope this helps more than makes a mess in the repo. 

Thanks again. 

Amanda

**Comment by samyeaman** [comment]
Thanks for letting me know, I'll fix that!

**Comment by Astahlke** [comment]
Still getting that unexpected comma error - I think because you need  `c()` at the beginning of the authors list. Thanks for getting to this quickly!

**Comment by samyeaman** [comment]
Thanks for letting me know and for the fix, I think I did it right now (?).
I'm a total github noob. I hope the package is useful to you! Happy to help
with any decisions on implementation if you have questions. What are you
working on?

**Comment by Astahlke** [comment]
Yep! Thanks again for getting to this and resolving the issue. I'll send you an email because I do have a few questions!
